### PR TITLE
fix: dropdown button stays pressed

### LINKED ISSUE #92: Light mode button does not stay pressed
Originally mentioned in #80

### PR DESCRIPTION
**Pull request by agazso**
Also replaces slots with snippets.
Fixes #92

### CODE REVIEW

File: src/lib/components/custom/dropdown.svelte [hunk 1]
```diff
@@ -1,11 +1,16 @@
 <script lang="ts">
+	import type { Snippet } from 'svelte'
+	import Button from '$lib/components/ui/button.svelte'
+
 	type Props = {
 		disabled?: boolean
 		up?: boolean
 		left?: boolean
+		button: Snippet
+		children: Snippet
```
Comment (vojtechsimetka) [inline src/lib/components/custom/dropdown.svelte:10]: Shouldn't the `children` be optional? I mean it works in TS, but not providing children may fail in JS
```suggestion
		children: Snippet
```

**Review by vojtechsimetka — APPROVED** [review]

File: src/lib/components/custom/dropdown.svelte (hunk 1 above)
Comment (agazso) [reply src/lib/components/custom/dropdown.svelte:10]: By this logic everything should be optional. We can do that, however I wanted to indicate here for Typescript users that the children is not optional, because without that the dropdown is just a sticky button, implemented in a convoluted way :)
