### PR TITLE
fix(select): bindable value, onchange and oninput events

### LINKED ISSUE #55: It is not clear how to use the value of Select
I tried `onchange`, `oninput` and `bind:value`, neither of them worked (bind is not even supported by the component).

### PR DESCRIPTION
**Pull request by vojtechsimetka**
resolves #55

### CODE REVIEW

File: src/lib/components/ui/select/select.svelte [hunk 1]
```diff
@@ -5,18 +5,23 @@
 	import { withSelectStore } from './select-store.svelte'
 
 	type Dimension = 'default' | 'large' | 'compact' | 'small'
-	interface Props extends HTMLInputAttributes {
+	interface Props extends Omit<HTMLInputAttributes, 'onchange' | 'oninput'> {
```
Comment (agazso) [inline src/lib/components/ui/select/select.svelte:8]: I am not sure the `onchange` and `oninput` is really needed if the value can be bound. I am also not a fan of changing the semantics of the existing functions.

For now I would just remove them. I was thinking about use-cases when you may want more customised UX, but they are more for text inputs. For those the best solution I found is to be able to provide a custom input element as default slot. For example: https://flowbite-svelte.com/docs/forms/input-field#Advanced_usage

**Review by agazso — APPROVED** [review]

File: src/lib/components/ui/select/select.svelte (hunk 1 above)
Comment (vojtechsimetka) [reply src/lib/components/ui/select/select.svelte]: Fair point, the `oninput` is definitely extra, `onchange` can be reason about. I removed them for now, but that means that these events are never triggered. 

We likely need a more thorough discussion what in general will be the in/out interfaces for inputs to be consistent.
